export const UPDATE_REGISRATION_LOCAL_DATA = 'UPDATE_REGISRATION_LOCAL_DATA'
export const UPDATE_REGISRATION_ERROR = "UPDATE_REGISRATION_ERROR"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const GET_RELIGION_DETAILS = 'GET_RELIGION_DETAILS'
export const UPDATE_RELIGION_DETAILS = 'UPDATE_RELIGION_DETAILS'
export const GET_SUB_RELIGION_DETAILS = 'GET_SUB_RELIGION_DETAILS'
export const UPDATE_SUB_RELIGION_DETAILS = 'UPDATE_SUB_RELIGION_DETAILS'
export const GET_CASTE_DETAILS = 'GET_CASTE_DETAILS'
export const UPDATE_CASTE_DETAILS = 'UPDATE_CASTE_DETAILS'
export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const VALIDATE_FIELDS = 'VALIDATE_FIELDS'

export const UPDATE_LOGIN_ERROR = 'UPDATE_LOGIN_ERROR'
export const AFTER_LOGIN_ERROR = 'AFTER_LOGIN_ERROR'
export const UPDATE_LOGIN_LOCAL_DATA= 'UPDATE_LOGIN_LOCAL_DATA'
export const LOGIN_USER= 'LOGIN_USER'

export const UPDATE_LOGIN_DATA = 'UPDATE_LOGIN_DATA'


